include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve
  page_width: 200

linter:
  rules:
    prefer_const_constructors: true
    directives_ordering: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    annotate_overrides: true
    annotate_redeclares: true
    avoid_relative_lib_imports: true
    camel_case_types: true
    combinators_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    file_names: true
    no_literal_bool_comparisons: true
    non_constant_identifier_names: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    unnecessary_string_interpolations: true
    unnecessary_statements: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    use_full_hex_values_for_flutter_colors: true
    use_is_even_rather_than_modulo: true
    use_key_in_widget_constructors: true
    use_named_constants: true
    use_super_parameters: true
    use_truncating_division: true
    valid_regexps: true
