name: expenselab
description: "ExpenseLab is a mobile-first personal finance management application designed to help users track income, expenses, savings, and budgets with an organic, modern, and intuitive interface. The app focuses on visual clarity and actionable insights to promote financial well-being."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
